### ISSUE TITLE
Cannot open saved diagram using AzureTemplate.v5.tb7

### ISSUE THREAD

**Issue by weixian-zhang** [AzureArchitecture/threat-model-templates#7]
**Describe the bug**
Using Azure stencils from AzureTemplate.v5.tb7, when opening a saved diagram an error occurred (below screenshot) causing diagram unable to open.

**To Reproduce**
* Use any one or more Azure stencils from template AzureTemplate.v5.tb7.
* save the diagram
* Open the diagram by double-clicking or Open option within Threat Modelling Tool

**Expected behavior**
Diagram should open correctly without error

**Screenshots**
![image](https://user-images.githubusercontent.com/43234101/167987742-50dee27c-8e47-4842-b636-e4cd5eb091f8.png)  
![image](https://user-images.githubusercontent.com/43234101/167987763-cfb52bb3-da36-4a4e-9eb0-09196d804711.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
Windows 11

**Comment by adirao99** [comment]
> **Describe the bug** Using Azure stencils from AzureTemplate.v5.tb7, when opening a saved diagram an error occurred (below screenshot) causing diagram unable to open.
> 
> **To Reproduce**
> 
> * Use any one or more Azure stencils from template AzureTemplate.v5.tb7.
> * save the diagram
> * Open the diagram by double-clicking or Open option within Threat Modelling Tool
> 
> **Expected behavior** Diagram should open correctly without error
> 
> **Screenshots** ![image](https://user-images.githubusercontent.com/43234101/167987742-50dee27c-8e47-4842-b636-e4cd5eb091f8.png) ![image](https://user-images.githubusercontent.com/43234101/167987763-cfb52bb3-da36-4a4e-9eb0-09196d804711.png)
> 
> **Desktop (please complete the following information):**
> 
> * OS: [e.g. iOS]
> * Browser [e.g. chrome, safari]
> * Version [e.g. 22]
> 
> **Smartphone (please complete the following information):** Windows 11

I am facing the same problem, could someone please help us or provide instructions on how to use the template? Need it for my work

**Comment by adirao99** [comment]
@PatrickGallucci I am also facing the same problem like weixian, could you please provide us with a workaround or fix? Thank you

**Comment by dmitrykarnitski** [comment]
Hi,

I applied one workaround that helped me at least, maybe it will be useful for someone else.

1. Open a diagram that is not opening using any text editor (e.g. notepad)
2. Find '<a:Version>' string
3. Replace System.String[] value with any version (e.g. 3.0)
4. Open a downloaded template using any text editor (e.g. notepad)
5. Find 'Manifest' node -> 'version' attribute
6. Replace System.String[] value with any version (e.g. 3.0) <-- make sure version is aligned with the version from the diagram

If you have only downloaded a template and have not started work on a diagram, then you are lucky and you can just apply steps 4-6 and the newly created diagram that is based on the template should be opening correctly (can't promise, but at least it works for me now).

**Comment by PatrickGallucci** [comment]
Thanks!
